### PR TITLE
Create kagi-hackerish-monokai-with-doggo

### PR DESCRIPTION
**Pull request by TheLastEnvoy**
Original CSS created by maxpl01t, I just put the doggo back on it

### CODE REVIEW

**Comment by kawaiier** [comment]
Hey @TheLastEnvoy!
I can't see any difference with the original theme on the search screen. Are they identical?

**Comment by TheLastEnvoy** [comment]
Hey! Yes, it's the same theme than hack monokai from maxpl01t, BUT, I removed the part that hides the doggo. The original CSS from maxpl01t hide the doggo from the mainscreen, I like his theme but I also like the doggo hahaha... So I just changed his CSS to show the doggo on the mainscreen.

**Comment by kawaiier** [comment]
I've added your alternative version right next to the original with the link to your repo

**Comment by TheLastEnvoy** [comment]
Great. I'm sorry if it was kinda redundant, it's the first time I upload something on Github. I'm really newbie with it.

**Pull request closed without merging**
